# NumPy - Matrices

In [2]:
import numpy as np

![alt](http://www.scatter.com/images/DataLab_logo.jpg)

## Matrix Arithmetic

In [5]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,1))
print ("X.shape =",X.shape)
print ("y.shape =",y.shape)

X.shape = (2, 3)
y.shape = (3, 1)

In [6]:
X

Out[ 38 ]: 
array([[1, 2, 3],
 [4, 5, 6]])

In [7]:
y

Out[ 42 ]: 
array([[1.],
 [1.],
 [1.]])

In [8]:
1000 + X

Out[ 40 ]: 
array([[1001, 1002, 1003],
 [1004, 1005, 1006]])

In [9]:
10 * X

Out[ 6 ]: 
array([[10, 20, 30],
 [40, 50, 60]])

In [10]:
X + X

Out[ 7 ]: 
array([[ 2, 4, 6],
 [ 8, 10, 12]])

In [11]:
10 ** X

Out[ 8 ]: 
array([[ 10, 100, 1000],
 [ 10000, 100000, 1000000]])

In [12]:
y ** 10

Out[ 43 ]: 
array([[1.],
 [1.],
 [1.]])

In [13]:
X * X

Out[ 10 ]: 
array([[ 1, 4, 9],
 [16, 25, 36]])

## Matrix Functions and Methods

Matrix multiplication 

- https://www.mathsisfun.com/algebra/matrix-multiplying.html

Notice the shapes of `X` and `y` (created above.)

In [17]:
(X.shape,
 y.shape
)

Out[ 11 ]: ((2, 3), (3, 1))

In [18]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,2))
print ("X.shape =",X.shape)
print ("y.shape =",y.shape)

X.shape = (2, 3)
y.shape = (3, 2)

In [19]:
X.dot(y)

Out[ 49 ]: 
array([[ 6., 6.],
 [15., 15.]])

__Exercises__: 
1. Take the dot product of a subset of `X` and the entire array `y` that equals `6`.
1. Take the dot product of a subset of `X` and the entire array `y` that equals `15`.
1. Take the dot product of the transpose of `y` and a subset of the transpose of `X` and that equals `6`.

Lookup the transpose function for Numpy arrays on the _Routines_ page:
- https://docs.scipy.org/doc/numpy/reference/routines.html

For each of the above items, you may want to create variables to hold the subsets or transposes. 

Your final result though should consist of a single line of code (for each item.)

In [21]:
X = np.array([[1,2,3],[4,5,6]])
y = np.ones((3,1))
(X.shape, y.shape)

Out[ 13 ]: ((2, 3), (3, 1))

In [22]:
X

Out[ 14 ]: 
array([[1, 2, 3],
 [4, 5, 6]])

In [23]:
y

Out[ 15 ]: 
array([[1.],
 [1.],
 [1.]])

In [24]:
np.sum(y)

Out[ 16 ]: 3.0

In [25]:
np.sum(X)

Out[ 17 ]: 21

In [26]:
np.sum(X, axis=0)

Out[ 18 ]: array([5, 7, 9])

In [27]:
np.sum(X, axis=1)

Out[ 19 ]: array([ 6, 15])

In [28]:
np.mean(X)

Out[ 20 ]: 3.5

In [29]:
np.mean(X, axis=0)

Out[ 21 ]: array([2.5, 3.5, 4.5])

In [30]:
np.mean(X, axis=1)

Out[ 22 ]: array([2., 5.])

In [31]:
np.mean(X[0,:])

Out[ 52 ]: 2.0

In [32]:
np.mean(X[:,0])

Out[ 24 ]: 2.5

__The End__